# Generated by Django 2.2 on 2022-04-28 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_products_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='age',
        ),
    ]
